use_frameworks!

platform :ios, '9.0'

target 'OsNetworking_Example' do
  pod 'OsNetworking', :path => '../'

  target 'OsNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
